name: Build and Deploy to GKE

on:
  push:
    branches:
      - master
#  workflow_dispatch:
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}    # cluster name
  GKE_ZONE: us-central1  # cluster zone
  IMAGE: chatwithconfluence  # image name
  IMAGE_TAG: v1 # image tag
  GAR_ZONE: us-central1-a # artifact registry zone
  GAR_REPO: chatwithconfluence # artifact registry repository
  # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  # CONFLUENCE_PRIVATE_API_KEY: ${{ secrets.CONFLUENCE_PRIVATE_API_KEY }}
  # CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
  # CONFLUENCE_SPACE_NAME: ${{ secrets.CONFLUENCE_SPACE_NAME }}
  # EMAIL_ADRESS: ${{ secrets.EMAIL_ADRESS }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: Docker configuration
      run: |-
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_ZONE-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG"

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CONFLUENCE_PRIVATE_API_KEY: ${{ secrets.CONFLUENCE_PRIVATE_API_KEY }}
        CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
        CONFLUENCE_SPACE_NAME: ${{ secrets.CONFLUENCE_SPACE_NAME }}
        EMAIL_ADRESS: ${{ secrets.EMAIL_ADRESS }}
        
      run: |
        echo "Creating Kubernetes Secret"
        kubectl create secret generic chatbot-app-secret \
          --from-literal=OPENAI_API_KEY=$OPENAI_API_KEY \
          --from-literal=CONFLUENCE_PRIVATE_API_KEY=$CONFLUENCE_PRIVATE_API_KEY \
          --from-literal=CONFLUENCE_SPACE_KEY=$CONFLUENCE_SPACE_KEY \
          --from-literal=CONFLUENCE_SPACE_NAME=$CONFLUENCE_SPACE_NAME \
          --from-literal=EMAIL_ADRESS=$EMAIL_ADRESS \
          --dry-run=client -o yaml | kubectl apply -f -
        
        echo "Deploying to Kubernetes"
        
        kubectl delete deployment chatwithconfluence
        kubectl apply -f deploy.yml
        kubectl get pods